---

# Since auditd rules are dependent on syscalls and syscall tables are architecture specific,
# we need to update the auditd rules depending on the architecture of the system.
# This task passed the syscalls table to the auditd template and updates the auditd rules

- name: "POST | AUDITD | Ensure use of privileged commands is collected"
  ansible.builtin.shell: |
    {%- set egrep_exclude = "(asdfmnop|{{ amazon2cis_priv_command_excluded_mounts | join('|') }})" -%}
    for i in $(df | grep '^/dev' | grep -Ev '{{ egrep_exclude }}' | awk '{ print $NF }'); do
      find $i -xdev -type f -perm /6000 2>/dev/null;
    done
  changed_when: false
  failed_when: false
  check_mode: false
  register: discovered_privileged_commands

- name: "POST | AUDITD | Check if auditd is immutable before changes"
  ansible.builtin.shell: auditctl -s | grep "enabled 2"
  changed_when: false
  failed_when: discovered_auditd_immutable_check.rc not in [ 0, 1 ]
  register: discovered_auditd_immutable_check

- name: POST | AUDITD | Apply auditd template - only required rules will be added
  ansible.builtin.template:
    src: audit/99_auditd.rules.j2
    dest: /etc/audit/rules.d/99_auditd.rules
    owner: root
    group: root
    mode: 'go-rwx'
  notify:
    - Audit_immutable_fact
    - Restart_auditd

- name: POST | AUDITD | Apply auditd template will for section 5.2.3 - only required rules will be added | stat file
  ansible.builtin.stat:
    path: /etc/audit/rules.d/98_auditd_exceptions.rules
  register: discovered_auditd_exception_file

- name: POST | Set up auditd user logging exceptions | setup file
  when:
    - amzn2023cis_allow_auditd_uid_user_exclusions
    - amzn2023cis_auditd_uid_exclude | length > 0
  ansible.builtin.template:
    src: audit/98_auditd_exception.rules.j2
    dest: /etc/audit/rules.d/98_auditd_exceptions.rules
    owner: root
    group: root
    mode: u-x,g-wx,o-rwx
  diff: '{{ discovered_auditd_exception_file.stat.exists }}'
  notify: Restart auditd
