---

- name: Configure and remount /tmp with appropriate options | not systemd tmp.mount
  when: not amzn2023cis_tmp_svc
  vars:
    mount_point: /tmp
  block:
    - name: Add filesystem options for /tmp
      ansible.posix.mount:
        path: '{{ mount_point }}'
        src: "{{ prelim_mount_point_fs_and_options[mount_point]['src'] }}"
        state: present
        fstype: "{{ prelim_mount_point_fs_and_options[mount_point]['fs_type'] }}"
        opts: "{{ prelim_mount_point_fs_and_options[mount_point]['options'] | unique | join(',') }}"

    - name: Remounting /tmp
      block:
        - name: Remounting /tmp | remount
          ansible.posix.mount:
            path: '{{ mount_point }}'
            state: remounted
      rescue:
        - name: /tmp mount busy, set reboot required fact
          ansible.builtin.set_fact:
            change_requires_reboot: true

        - name: /tmp mount busy, reboot required to apply changes | Warning
          ansible.builtin.debug:
            msg: 'Warning: /tmp mount busy, reboot required to apply changes'

        - name: /tmp mount busy, reboot required to apply changes
          ansible.builtin.import_tasks:
            file: warning_facts.yml
          vars:
            warn_control_id: /tmp mount busy, reboot required

- name: Reloading /tmp systemd service
  when: amzn2023cis_tmp_svc
  block:
    - name: Reloading /tmp systemd service | reload
      ansible.builtin.systemd:
        name: tmp.mount
        state: reloaded
        enabled: true
        masked: false
        daemon_reload: true
  rescue:
    - name: /tmp mount busy, set reboot required fact | systemd
      ansible.builtin.set_fact:
        change_requires_reboot: true

    - name: /tmp mount busy, reboot required to apply changes | Warning | systemd
      ansible.builtin.debug:
        msg: 'Warning: /tmp mount busy, reboot required to apply changes'

    - name: /tmp mount busy, reboot required to apply changes | systemd
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: /tmp mount busy, reboot required
