---
# handlers file for AMAZON2023-CIS

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Sysctl flush ipv4 route table
  when:
    - amzn2023cis_flush_ipv4_route
    - not system_is_container
  ansible.posix.sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: true
  ignore_errors: true  # noqa ignore-errors

- name: Sysctl flush ipv6 route table
  when:
    - amzn2023cis_flush_ipv6_route
    - not system_is_container
  ansible.posix.sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: true

- name: Systemd restart tmp.mount
  ansible.builtin.systemd:
    name: tmp.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded

- name: Remount tmp
  ansible.posix.mount:
    path: /tmp
    state: remounted

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted

- name: Grub2cfg
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: true
  ignore_errors: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart systemd_journal_upload
  ansible.builtin.systemd:
    name: systemd-journal-upload
    state: restarted

- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon-reload: true

- name: Audit_immutable_fact
  when: discovered_auditd_immutable_check.rc == 0
  ansible.builtin.debug:
    msg: "Reboot required for auditd to apply new rules as immutable set"
  notify: Change_requires_reboot

- name: Auditd rules reload
  when: discovered_auditd_immutable_check.rc == 1 or discovered_augenrules_check.stdout is search('No change')
  ansible.builtin.command: augenrules --load
  changed_when: true
  failed_when: discovered_augenrule_load.rc not in [ 0, 1 ]
  register: discovered_augenrule_load

- name: Restart auditd # noqa: command-instead-of-module
  ansible.builtin.command: /sbin/service auditd restart
  changed_when: true

- name: Change_requires_reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true
