---

# Skips if mount is absent
- name: 1.1.8.1 | AUDIT | Ensure /dev/shm is a separate partition
  when: amzn2023cis_rule_1_1_8_1
  tags:
    - level1-server
    - audit
    - mounts
    - rule_1.1.8.1
    - NIST800-53R5_CM-7
  vars:
    required_mount: /dev/shm
  block:
    - name: 1.1.8.1 | AUDIT | Ensure /dev/shm is a separate partition | Absent
      ansible.builtin.debug:
        msg: Warning!! {{ required_mount }} doesn't exist. This is a manual task

    - name: 1.1.8.1 | AUDIT | Ensure /dev/shm is a separate partition | Present
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: 1.1.8.1

- name: 1.1.8.2 | PATCH | Ensure nodev option set on /dev/shm partition
  when:
    - prelim_mount_point_fs_and_options[mount_point] is defined
    - amzn2023cis_rule_1_1_8_2
  tags:
    - level1-server
    - patch
    - mounts
    - rule_1.1.8.2
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  vars:
    mount_point: /dev/shm
    required_option: nodev
  notify: &mount_option_notify
    - Remount {{ mount_point }}
  ansible.builtin.set_fact: &mount_option_set_fact
    prelim_mount_point_fs_and_options: |
      {{ prelim_mount_point_fs_and_options | combine({mount_point: {'options': (prelim_mount_point_fs_and_options[mount_point]['options'] + [required_option])}}, recursive=True) }}
  changed_when: &mount_option_changed_when
    - required_option not in prelim_mount_point_fs_and_options[mount_point]['original_options']

- name: 1.1.8.3 | PATCH | Ensure noexec option set on /dev/shm partition
  when:
    - prelim_mount_point_fs_and_options[mount_point] is defined
    - amzn2023cis_rule_1_1_8_3
  tags:
    - level1-server
    - patch
    - mounts
    - rule_1.1.8.3
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  vars:
    mount_point: /dev/shm
    required_option: noexec
  notify: *mount_option_notify
  ansible.builtin.set_fact:
    <<: *mount_option_set_fact
  changed_when: *mount_option_changed_when

- name: 1.1.8.4 | PATCH | Ensure nosuid option set on /dev/shm partition
  when:
    - prelim_mount_point_fs_and_options[mount_point] is defined
    - amzn2023cis_rule_1_1_8_4
  tags:
    - level1-server
    - patch
    - mounts
    - rule_1.1.8.4
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  vars:
    mount_point: /dev/shm
    required_option: nosuid
  notify: *mount_option_notify
  ansible.builtin.set_fact:
    <<: *mount_option_set_fact
  changed_when: *mount_option_changed_when
